import Head from "next/head";
import React, { type ReactNode } from "react";

// Define the styles for the header using TailwindCSS classes
const Header = () => (
  <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
    Book <span className="text-[hsl(280,100%,70%)]">Live</span> Gig
  </h1>
);

// Define the styles for the footer using TailwindCSS classes
const Footer = () => (
  <div className="bg-gray-900 p-4 text-white">
    <p>Footer</p>
  </div>
);

type Props = {
  children: ReactNode;
};

// Define the overall layout of the app
export const Layout: React.FC<Props> = ({ children }: Props) => {
  return (
    <>
      <Head>
        <title>Book Live Gig</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-purple-900 to-indigo-900">
        <div className="max-w-xl w-full px-4 py-16 text-white">
          <Header />
          <div className="flex-1">{children}</div>
          <Footer />
        </div>
      </main>
    </>
  );
};
